services:
  - type: web
    name: moviestore
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TRAILER_FONT_PATH
        value: /opt/render/project/src/fonts
